# Build stage
FROM node:lts-buster AS build

# Set working directory
WORKDIR /usr/src/app

# Copy dependency definitions
COPY package.json ./

# Install dependencies
RUN npm install 

# Copy all files
COPY . .

# Build the app
RUN npm run build

# Production stage
FROM nginx:alpine

# Copy the build output to replace the default nginx contents.
COPY --from=build /usr/src/app/dist /usr/share/nginx/html

# Expose the port nginx is running on
EXPOSE 80

# Run nginx
CMD ["nginx", "-g", "daemon off;"]