version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "4000:80"
    depends_on:
      - api
    networks:
      - app-network

  api:
    build:
      context: ./api
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mydatabase
    networks:
      - app-network

  db:
    build:
      context: ./database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: nice-tile-server
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
